### ISSUE TITLE
Background Image not Rendering dynamically

### ISSUE THREAD

**Issue by Fatima-hub333** [emmiiorji/emmanuel_orji-ihuoma#16]
Hi @emmiiorji 

- You did a great job in completing your portfolio. There are some issues which you need to resolve. You are almost here:-)

-I saw that you are trying to style the background image via inline CSS within your innerHTML. JavaScript is not accepting inline CSS so you should assign the InnerHTML with required classes & after assigning target the element & style it with JavaScript functions.

**Comment by emmiiorji** [comment]
This has been fixed. Thank you.
